# Generated by Django 5.1.15 on 2026-08-27 14:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='Sequential attempt number for this booking (1, 2, 3...)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('800.00'), help_text='Fixed 30-day seat fee (₹800.00)', max_digits=8)),
                ('payment_mode', models.CharField(choices=[('MANUAL_UPI', 'Manual UPI')], default='MANUAL_UPI', max_length=20)),
                ('utr_number', models.CharField(blank=True, db_index=True, help_text='Bank transaction reference (UTR) provided by student', max_length=64, null=True)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Optional payment screenshot uploaded by student', null=True, upload_to='payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_VERIFICATION', max_length=25)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp of verification or rejection', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason provided by admin if payment was rejected')),
                ('booking', models.ForeignKey(help_text='Canonical booking linked to this payment attempt', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bookings.booking')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin user who verified or rejected this payment attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['booking', 'attempt_number'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, help_text='Sequential receipt number (e.g. BLL-202608-0042)', max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=150)),
                ('student_phone', models.CharField(max_length=15)),
                ('seat_number', models.PositiveSmallIntegerField()),
                ('membership_start', models.DateTimeField()),
                ('membership_expires_at', models.DateTimeField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_mode', models.CharField(default='MANUAL_UPI', max_length=20)),
                ('utr_reference', models.CharField(blank=True, max_length=64)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(help_text='The verified payment attempt this receipt is issued for', on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', Decimal('800.00'))), name='fixed_fee_800_rupees'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('booking', 'attempt_number'), name='unique_attempt_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING_VERIFICATION')), fields=('booking',), name='unique_pending_payment_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('utr_number__isnull', False), models.Q(('utr_number', ''), _negated=True)), fields=('utr_number',), name='unique_non_null_utr_number'),
        ),
    ]
