# Generated by Django 5.1.15 on 2026-08-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSequence',
            fields=[
                ('year_month', models.CharField(help_text='YYYYMM format (e.g. 202608)', max_length=6, primary_key=True, serialize=False)),
                ('last_sequence_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt Sequence',
                'verbose_name_plural': 'Receipt Sequences',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when student submitted payment proof (UTR / screenshot)', null=True),
        ),
    ]
