# Generated by Django 5.1.15 on 2026-08-27 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_reference', models.CharField(db_index=True, help_text='Unique booking reference (e.g. BKG-202608-0142)', max_length=32, unique=True)),
                ('hold_created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when temporary seat hold was initiated')),
                ('hold_expires_at', models.DateTimeField(db_index=True, help_text='Deadline by which payment must be verified before hold expires')),
                ('membership_start', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when Admin verified payment and paid membership started', null=True)),
                ('membership_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Exact timestamp when 30-calendar-day membership expires', null=True)),
                ('grace_until', models.DateTimeField(blank=True, db_index=True, help_text='Exact timestamp when 48-hour post-expiry grace period ends', null=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment Verification'), ('CONFIRMED', 'Confirmed (Active Membership)'), ('EXPIRING_SOON', 'Expiring Soon'), ('GRACE_PERIOD', 'Grace Period (48 Hours)'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_PAYMENT', max_length=25)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Quick boolean index to filter active vs archived bookings')),
                ('reminder_4d_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when 4-day renewal reminder email was sent', null=True)),
                ('reminder_3d_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when 3-day renewal reminder email was sent', null=True)),
                ('seat', models.ForeignKey(help_text='Assigned study seat (1 to 150)', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='seats.seat')),
                ('student', models.ForeignKey(help_text='Canonical student owner of this booking', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('hold_expires_at__gt', models.F('hold_created_at'))), name='hold_expiry_after_hold_start'), models.CheckConstraint(condition=models.Q(('membership_expires_at__isnull', True), ('membership_expires_at__gt', models.F('membership_start')), _connector='OR'), name='membership_expiry_after_start'), models.CheckConstraint(condition=models.Q(('grace_until__isnull', True), ('grace_until__gt', models.F('membership_expires_at')), _connector='OR'), name='grace_until_after_membership_expiry'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_PAYMENT', 'CONFIRMED', 'EXPIRING_SOON', 'GRACE_PERIOD'])), fields=('seat',), name='unique_active_booking_per_seat'), models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING_PAYMENT', 'CONFIRMED', 'EXPIRING_SOON', 'GRACE_PERIOD'])), fields=('student',), name='unique_active_booking_per_student')],
            },
        ),
    ]
