# Generated by Django 5.1.15 on 2026-08-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(db_index=True, help_text='Unique ticket identifier (e.g. TKT-202608-0012)', max_length=32, unique=True)),
                ('category', models.CharField(choices=[('AC_COOLING', 'AC / Cooling & Temperature'), ('CHAIR_DESK', 'Chair / Desk Furniture'), ('POWER_SOCKET', 'Power Socket / Electrical'), ('LIGHTING', 'Lighting'), ('WIFI_INTERNET', 'WiFi / Internet'), ('NOISE', 'Noise / Discipline'), ('CLEANLINESS', 'Cleanliness & Hygiene'), ('OTHER', 'Other Issue')], default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes recorded by admin upon investigating/resolving')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(blank=True, help_text='Associated study seat (optional if complaint is for general amenities)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='seats.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
