# Generated by Django 5.1.15 on 2026-08-27 15:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(choices=[('GENERAL', 'General Experience'), ('STUDY_ENVIRONMENT', 'Study Environment & Silence'), ('AIR_CONDITIONING', 'AC & Temperature'), ('CLEANLINESS', 'Cleanliness & Hygiene'), ('WIFI_FACILITY', 'WiFi & Digital Facilities'), ('STAFF_SUPPORT', 'Staff & Management Support'), ('OTHER', 'Other')], default='GENERAL', max_length=50)),
                ('description', models.TextField(help_text='Detailed feedback or suggestions')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False, help_text='Flag indicating if admin has reviewed this feedback')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes by admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_between_1_and_5')],
            },
        ),
    ]
