# Generated by Django 5.1.15 on 2026-08-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HELD', 'Held (Payment Pending)'), ('BOOKED', 'Booked (Active Membership)'), ('MAINTENANCE', 'Under Maintenance')], db_index=True, default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('has_power_socket', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 150)), name='seat_number_strictly_1_to_150')],
            },
        ),
        migrations.CreateModel(
            name='SeatMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='seats.seat')),
            ],
            options={
                'verbose_name': 'Seat Maintenance Log',
                'verbose_name_plural': 'Seat Maintenance Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
