# Generated by Django 5.1.15 on 2026-08-27 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('RENEWAL_REMINDER_4D', 'Renewal Reminder (4 Days Before Expiry)'), ('RENEWAL_REMINDER_3D', 'Renewal Reminder (3 Days Before Expiry)'), ('GRACE_WARNING', 'Grace Period Warning'), ('PAYMENT_VERIFIED', 'Payment Verified & Membership Activated'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('BOOKING_CONFIRMED', 'Seat Booking Confirmed'), ('SEAT_RELEASED', 'Seat Auto-Released'), ('COMPLAINT_UPDATE', 'Complaint Status Update')], max_length=40)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App Notification')], default='EMAIL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
